name: "check"
on:
  push:
jobs:
  check:
    needs:
      - bash-variable
      - hash
      - isolated
    runs-on: ubuntu-latest
    steps:
      - run: echo check
  bash-variable:
    needs:
      - bash-variable-0
      - bash-variable-1
    runs-on: ubuntu-latest
    steps:
      - run: echo bash-variable
  bash-variable-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@a4b8aaf5a24260b643f571235829e53e6b3cc920
      - run: cd test && nix develop --command bash-variable-0
  bash-variable-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@a4b8aaf5a24260b643f571235829e53e6b3cc920
      - run: cd test && nix develop --command bash-variable-1
  hash:
    needs:
      - hash-0
    runs-on: ubuntu-latest
    steps:
      - run: echo hash
  hash-0 :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@a4b8aaf5a24260b643f571235829e53e6b3cc920
      - run: cd test && nix develop --command isolated-000
  isolated:
    needs:
      - isolated-000
      - isolated-001
      - isolated-010
      - isolated-011
    runs-on: ubuntu-latest
    steps:
      - run: echo isolated
  isolated-000:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@a4b8aaf5a24260b643f571235829e53e6b3cc920
      - run: cd test && nix develop --command isolated-000
  isolated-001:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@a4b8aaf5a24260b643f571235829e53e6b3cc920
      - run: cd test && nix develop --command isolated-001
  isolated-010:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@a4b8aaf5a24260b643f571235829e53e6b3cc920
      - run: cd test && nix develop --command isolated-010
  isolated-011:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@a4b8aaf5a24260b643f571235829e53e6b3cc920
      - run: cd test && nix develop --command isolated-011
