name: "check"
on:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@a4b8aaf5a24260b643f571235829e53e6b3cc920
      - run: cd test && nix develop --command isolated-0000
